bots_data = [
    # CODING
    {"name": "Grok-4", "category": "Coding", "poe_url": "https://poe.com/Grok-4", "description": "xAI's latest model, excellent for complex coding tasks, debugging, and system design.", "strengths": ["debugging", "system design", "code generation", "TypeScript", "Python"], "tags": ["coding", "advanced", "general"]},
    {"name": "GPT-5.2", "category": "Coding", "poe_url": "https://poe.com/GPT-5.2", "description": "OpenAI's powerful model for coding, strong at multi-step reasoning and code generation.", "strengths": ["code generation", "multi-step reasoning", "Python", "JavaScript", "APIs"], "tags": ["coding", "advanced", "general"]},
    {"name": "Gemini-3-Pro", "category": "Coding", "poe_url": "https://poe.com/Gemini-3-Pro", "description": "Google's Gemini Pro model, great for coding with large context windows.", "strengths": ["large context", "code review", "Python", "Java", "refactoring"], "tags": ["coding", "advanced"]},
    {"name": "Claude-Sonnet-4.5", "category": "Coding", "poe_url": "https://poe.com/Claude-Sonnet-4.5", "description": "Anthropic's Claude Sonnet, excellent for clean code, documentation, and code explanation.", "strengths": ["clean code", "documentation", "code explanation", "Python", "TypeScript"], "tags": ["coding", "writing", "intermediate"]},
    {"name": "GPT-4.1", "category": "Coding", "poe_url": "https://poe.com/GPT-4.1", "description": "Reliable OpenAI model for everyday coding tasks and debugging.", "strengths": ["debugging", "code generation", "JavaScript", "Python", "SQL"], "tags": ["coding", "intermediate"]},
    {"name": "DeepSeek-V3", "category": "Coding", "poe_url": "https://poe.com/DeepSeek-V3", "description": "DeepSeek's efficient model, great for coding with strong performance at low cost.", "strengths": ["code generation", "Python", "C++", "algorithms", "efficiency"], "tags": ["coding", "efficient", "intermediate"]},
    {"name": "Claude-Haiku-4.5", "category": "Coding", "poe_url": "https://poe.com/Claude-Haiku-4.5", "description": "Fast and lightweight Claude model for quick coding tasks and snippets.", "strengths": ["quick snippets", "fast responses", "Python", "JavaScript", "boilerplate"], "tags": ["coding", "fast", "lightweight"]},
    {"name": "GPT-5.3-Codex", "category": "Coding", "poe_url": "https://poe.com/GPT-5.3-Codex", "description": "OpenAI Codex-based model specialized exclusively for code generation and software engineering.", "strengths": ["code generation", "autocomplete", "Python", "JavaScript", "code completion"], "tags": ["coding", "specialized", "advanced"]},
    {"name": "o4-mini", "category": "Coding", "poe_url": "https://poe.com/o4-mini", "description": "OpenAI reasoning model optimized for coding and math, fast and efficient.", "strengths": ["reasoning", "algorithms", "math", "Python", "competitive programming"], "tags": ["coding", "math", "reasoning", "fast"]},
    {"name": "o3-pro", "category": "Coding", "poe_url": "https://poe.com/o3-pro", "description": "OpenAI's most powerful reasoning model for extremely hard coding and logic problems.", "strengths": ["hard problems", "reasoning", "algorithms", "competitive programming", "system design"], "tags": ["coding", "advanced", "reasoning"]},
    {"name": "Kimi-K2.5", "category": "Coding", "poe_url": "https://poe.com/Kimi-K2.5", "description": "Moonshot AI model with strong coding and long-context capabilities.", "strengths": ["long context", "code generation", "Python", "C", "refactoring"], "tags": ["coding", "long-context"]},

    # WRITING
    {"name": "GPT-5.2-Instant", "category": "Writing", "poe_url": "https://poe.com/GPT-5.2-Instant", "description": "Fast version of GPT-5.2, great for quick writing tasks, emails, and content drafts.", "strengths": ["fast writing", "emails", "content drafts", "summaries", "casual writing"], "tags": ["writing", "fast", "productivity"]},
    {"name": "GPT-4o", "category": "Writing", "poe_url": "https://poe.com/GPT-4o", "description": "Balanced OpenAI model for creative and professional writing tasks.", "strengths": ["creative writing", "professional writing", "storytelling", "editing", "tone adjustment"], "tags": ["writing", "creative", "general"]},
    {"name": "ChatGPT-Essay-Writer", "category": "Writing", "poe_url": "https://poe.com/ChatGPT-Essay-Writer", "description": "Specialized bot for writing structured academic essays and arguments.", "strengths": ["essays", "academic writing", "arguments", "structure", "citations"], "tags": ["writing", "academic", "specialized"]},
    {"name": "HumanWrite10.0", "category": "Writing", "poe_url": "https://poe.com/HumanWrite10.0", "description": "Designed to produce human-sounding writing that bypasses AI detection.", "strengths": ["human-like writing", "AI bypass", "natural tone", "blogs", "articles"], "tags": ["writing", "humanize", "specialized"]},
    {"name": "FullBook-Writer", "category": "Writing", "poe_url": "https://poe.com/FullBook-Writer", "description": "Specialized for long-form book and novel writing with narrative continuity.", "strengths": ["long-form", "novels", "narrative", "chapters", "storytelling"], "tags": ["writing", "creative", "long-form"]},
    {"name": "Suno-Writer", "category": "Writing", "poe_url": "https://poe.com/Suno-Writer", "description": "Specialized bot for writing song lyrics and music content.", "strengths": ["lyrics", "songs", "rhymes", "music", "creative writing"], "tags": ["writing", "music", "creative", "specialized"]},
    {"name": "Jailbreak-Bot-4.5", "category": "Writing", "poe_url": "https://poe.com/Jailbreak-Bot-4.5", "description": "Fewer content restrictions for creative fiction, mature themes, and unrestricted writing.", "strengths": ["unrestricted writing", "fiction", "mature themes", "creative freedom"], "tags": ["writing", "creative", "unrestricted"]},

    # RESEARCH
    {"name": "o3-deep-research", "category": "Research", "poe_url": "https://poe.com/o3-deep-research", "description": "OpenAI's o3 model with deep research capabilities, browses the web for thorough answers.", "strengths": ["deep research", "web browsing", "citations", "fact-checking", "academic topics"], "tags": ["research", "advanced", "web"]},
    {"name": "Exa-Research", "category": "Research", "poe_url": "https://poe.com/Exa-Research", "description": "Uses Exa's neural search engine to find and synthesize high-quality web sources.", "strengths": ["web search", "source synthesis", "citations", "academic papers", "technical research"], "tags": ["research", "web", "specialized"]},
    {"name": "Reka-Research", "category": "Research", "poe_url": "https://poe.com/Reka-Research", "description": "Reka AI's research assistant for summarizing and analyzing complex topics.", "strengths": ["summarization", "analysis", "complex topics", "document review"], "tags": ["research", "analysis"]},
    {"name": "Gemini-Deep-Research", "category": "Research", "poe_url": "https://poe.com/Gemini-Deep-Research", "description": "Google Gemini with deep research mode, leverages Google's search for comprehensive reports.", "strengths": ["Google search", "comprehensive reports", "fact-checking", "current events"], "tags": ["research", "web", "advanced"]},
    {"name": "Perplexity-deep-research", "category": "Research", "poe_url": "https://poe.com/Perplexity-deep-research", "description": "Perplexity's deep research bot with cited, real-time web search answers.", "strengths": ["real-time web", "citations", "current events", "fact-checking", "news"], "tags": ["research", "web", "citations"]},
    {"name": "o4-mini-deep-research", "category": "Research", "poe_url": "https://poe.com/o4-mini-deep-research", "description": "Lightweight but powerful research model from OpenAI with web access.", "strengths": ["fast research", "web access", "summaries", "quick answers"], "tags": ["research", "fast", "web"]},
    {"name": "Web-Search", "category": "Research", "poe_url": "https://poe.com/Web-Search", "description": "Simple web search bot for real-time information retrieval.", "strengths": ["real-time info", "current events", "quick lookups", "news"], "tags": ["research", "web", "simple"]},
    {"name": "GPT-Researcher", "category": "Research", "poe_url": "https://poe.com/GPT-Researcher", "description": "Autonomous research agent that generates detailed reports from multiple web sources.", "strengths": ["autonomous research", "multi-source", "detailed reports", "academic"], "tags": ["research", "advanced", "autonomous"]},
    {"name": "Linkup-Deep-Search", "category": "Research", "poe_url": "https://poe.com/Linkup-Deep-Search", "description": "Deep search bot using Linkup's API for high-quality sourced research.", "strengths": ["deep search", "sourced answers", "web links", "research"], "tags": ["research", "web", "sourced"]},

    # IMAGE GENERATION
    {"name": "Nano-Banana", "category": "Image Generation", "poe_url": "https://poe.com/Nano-Banana", "description": "Google Gemini-based image generation, fast and high quality for general image tasks.", "strengths": ["general images", "fast", "photorealistic", "illustrations"], "tags": ["image", "fast", "general"]},
    {"name": "Nano-Banana-Pro", "category": "Image Generation", "poe_url": "https://poe.com/Nano-Banana-Pro", "description": "Pro version of Nano-Banana, higher quality and more detailed image generation.", "strengths": ["high quality", "detailed", "photorealistic", "artistic"], "tags": ["image", "advanced", "pro"]},
    {"name": "GPT-Image-1.5", "category": "Image Generation", "poe_url": "https://poe.com/GPT-Image-1.5", "description": "OpenAI's DALL-E based image generator, excellent for creative and concept art.", "strengths": ["concept art", "creative", "text in images", "logos", "illustrations"], "tags": ["image", "creative", "advanced"]},
    {"name": "Grok-Imagine-Image", "category": "Image Generation", "poe_url": "https://poe.com/Grok-Imagine-Image", "description": "xAI's image generation model, strong at realistic and stylized images.", "strengths": ["realistic", "stylized", "portraits", "scenes"], "tags": ["image", "realistic"]},
    {"name": "Imagen-4", "category": "Image Generation", "poe_url": "https://poe.com/Imagen-4", "description": "Google's Imagen 4 model, state-of-the-art photorealistic image generation.", "strengths": ["photorealistic", "high resolution", "people", "landscapes"], "tags": ["image", "advanced", "photorealistic"]},
    {"name": "Image-4-Ultra", "category": "Image Generation", "poe_url": "https://poe.com/Image-4-Ultra", "description": "Ultra version of Imagen 4 for highest quality photorealistic outputs.", "strengths": ["ultra quality", "photorealistic", "commercial use", "detailed scenes"], "tags": ["image", "pro", "photorealistic"]},
    {"name": "Kling-Image-01", "category": "Image Generation", "poe_url": "https://poe.com/Kling-Image-01", "description": "Kling's image generation model, strong for stylized and anime-style images.", "strengths": ["anime", "stylized", "creative", "characters"], "tags": ["image", "anime", "stylized"]},
    {"name": "Qwen-Image", "category": "Image Generation", "poe_url": "https://poe.com/Qwen-Image", "description": "Alibaba's Qwen image model, good for general and Asian-style art generation.", "strengths": ["general images", "Asian art style", "illustrations", "characters"], "tags": ["image", "general", "stylized"]},

    # MATH/SCIENCE
    {"name": "DeepSeek-R1", "category": "Math/Science", "poe_url": "https://poe.com/DeepSeek-R1", "description": "DeepSeek's reasoning model, exceptional for math proofs, science problems, and logic.", "strengths": ["math proofs", "calculus", "physics", "reasoning", "step-by-step"], "tags": ["math", "science", "reasoning", "advanced"]},
    {"name": "ChatGPT-Math-Solver", "category": "Math/Science", "poe_url": "https://poe.com/ChatGPT-Math-Solver", "description": "Specialized bot for solving math problems step-by-step with clear explanations.", "strengths": ["step-by-step", "algebra", "calculus", "geometry", "explanations"], "tags": ["math", "specialized", "education"]},
    {"name": "ChatGPT-Science", "category": "Math/Science", "poe_url": "https://poe.com/ChatGPT-Science", "description": "Specialized for science topics including physics, chemistry, and biology.", "strengths": ["physics", "chemistry", "biology", "science explanations", "formulas"], "tags": ["science", "specialized", "education"]},
    {"name": "o3-mini", "category": "Math/Science", "poe_url": "https://poe.com/o3-mini", "description": "OpenAI reasoning model optimized for math and science, fast and accurate.", "strengths": ["math", "reasoning", "fast", "algorithms", "logic"], "tags": ["math", "reasoning", "fast"]},

    # BUSINESS/PRODUCTIVITY
    {"name": "Business-Logo-Bot", "category": "Business/Productivity", "poe_url": "https://poe.com/Business-Logo-Bot", "description": "Generates business logos and brand identity concepts.", "strengths": ["logos", "branding", "business identity", "design concepts"], "tags": ["business", "design", "specialized"]},
    {"name": "Sonic-3.0", "category": "Business/Productivity", "poe_url": "https://poe.com/Sonic-3.0", "description": "Fast productivity bot for summarization, emails, meeting notes, and business tasks.", "strengths": ["summarization", "emails", "meeting notes", "productivity", "fast"], "tags": ["business", "productivity", "fast"]},
    {"name": "Powerpoint_fast_V2", "category": "Business/Productivity", "poe_url": "https://poe.com/Powerpoint_fast_V2", "description": "Generates PowerPoint presentation outlines and slide content quickly.", "strengths": ["presentations", "slides", "outlines", "business decks"], "tags": ["business", "productivity", "specialized"]},
    {"name": "GLM-5", "category": "Business/Productivity", "poe_url": "https://poe.com/GLM-5", "description": "Zhipu AI's GLM model, capable general assistant for business and productivity tasks.", "strengths": ["general assistant", "business writing", "analysis", "multilingual"], "tags": ["business", "general", "multilingual"]},
    {"name": "DeepSeek-V3.2-Omni", "category": "Business/Productivity", "poe_url": "https://poe.com/DeepSeek-V3.2-Omni", "description": "Omni version of DeepSeek V3 for multimodal business tasks including document and image analysis.", "strengths": ["multimodal", "document analysis", "business reports", "data extraction"], "tags": ["business", "multimodal", "advanced"]},

    # FUN/CREATIVE
    {"name": "Qwen3-Max-Thinking", "category": "Fun/Creative", "poe_url": "https://poe.com/Qwen3-Max-Thinking", "description": "Qwen's thinking model, great for creative brainstorming and complex fun challenges.", "strengths": ["brainstorming", "creative ideas", "thinking out loud", "roleplay"], "tags": ["fun", "creative", "thinking"]},
    {"name": "ElevenLabs-v3", "category": "Fun/Creative", "poe_url": "https://poe.com/ElevenLabs-v3", "description": "ElevenLabs voice generation bot for creating realistic AI voiceovers and audio.", "strengths": ["voice generation", "audio", "voiceovers", "text to speech"], "tags": ["fun", "audio", "specialized"]},
    {"name": "Sora-2-Pro", "category": "Fun/Creative", "poe_url": "https://poe.com/Sora-2-Pro", "description": "OpenAI's Sora video generation model for creating short AI-generated videos.", "strengths": ["video generation", "short clips", "creative videos", "animations"], "tags": ["fun", "video", "creative", "advanced"]},
    {"name": "ProfessurGPT", "category": "Fun/Creative", "poe_url": "https://poe.com/ProfessurGPT", "description": "Professor persona bot for educational explanations and academic tutoring in a fun way.", "strengths": ["tutoring", "explanations", "education", "academic", "fun learning"], "tags": ["fun", "education", "persona"]},
    {"name": "Python", "category": "Fun/Creative", "poe_url": "https://poe.com/Python", "description": "Python code executor bot — run Python code directly in the chat.", "strengths": ["run code", "Python execution", "quick scripts", "data analysis"], "tags": ["fun", "coding", "specialized"]},
]
